config/routes.rb
MoneyManagement::Application.routes.draw do
  
  resources :bills
  
  resources :user_bills do
    get :mark_as_paid
  end

  match '/users/login' => 'users#login'
  match '/users/logout' => 'users#logout'
  match '/users/welcome' => 'users#welcome'
  match '/user_bills/mark_as_paid' => 'user_bills#mark_as_paid'

  resources :users do
    get :login
    post :login
  end
    
  get "admin/index"

  root :to => "users#welcome"
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :user_bills, :dependent => :destroy
  has_many :bills, :through => :user_bills
  
  validates_presence_of :username, :password
  validates_uniqueness_of :username

  def self.authenticate(username, pass)
    u = find(:first, :conditions => ["username = ? AND password = ?", username, pass])
    return nil if u.nil?
    return u
    nil
  end
  
  def to_s
    username
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :login_required, :only => ['welcome', 'hidden']

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    admin_required
    @user = User.find(params[:id])
    @user_bills = UserBill.where("user_id = ?", params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
  
  # GET /users/new
  # GET /users/new.xml
  def new
    admin_required
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    admin_required
    @user = User.find(params[:id])
  end
  
  # PUT /users/1
  # PUT /users/1.xml
  def update
    admin_required
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    admin_required
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  def login
    if session[:user]
      redirect_to(users_welcome_path)
    end
    if request.post?
      if session[:user] = User.authenticate(params[:user][:username], params[:user][:password])
        flash[:message] = "Login successful"
        redirect_to(users_welcome_path, :notice => "Login Successful")
      else
        redirect_to(users_login_path, :notice => "Login unsuccessful")
      end
    end
  end

  def logout
    session[:user] = nil
    flash[:message] = 'Logged out'
    redirect_to :action => 'login'
  end
  
  def welcome
    @user = User.find(current_user)
    @user_bills = UserBill.where("user_id = ?", @user)
    @sum = 0
    @user_bills.each { |b| add_amount(b) }
  end

  def hidden
  end
  
  private
  
  def add_amount (b)
    if !b.paid
      @sum = @sum + b.bill.amount.to_d
    end
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.haml
= semantic_form_for @user do |f|
  = f.inputs
  = f.buttons

app/views/users/edit.html.haml
- content_for(:title, 'Edit User')

%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
- content_for(:title, 'Manage Users')

%h1 Listing Users

%table
  %tr
    %th Username
    %th Admin
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.admin
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New User', new_user_path

app/views/users/login.html.haml
- content_for(:title, 'Login')

%h1 Login

%form{ :action => "login", :method => "post" }

  %fieldset
    %label{ :for => "user_username" } Username:
    %input{ :type => "text", :size => "20", :name => "user[username]" }
  
  %fieldset
    %label{ :for => "user_password" } Password:
    %input{ :type => "password", :size => "20", :name => "user[password]" }
  
  %fieldset
    %button{ :type => "submit" } Login

app/views/users/logout.html.haml
%h1 User#logout
%p Find me in app/views/user/logout.html.haml

app/views/users/new.html.haml
- content_for(:title, 'New User')

%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
- content_for(:title, 'User')

%p#notice= notice

%p
  %b Username:
  = @user.username

%h1 Bills

%table
  %tr
    %th Amount
    %th Name
    %th Description
    %th Paid
    %th Due

  - @user_bills.each do |user_bill|
    %tr
      %td= user_bill.bill.amount
      %td= user_bill.bill.name
      %td= user_bill.bill.description
      - if user_bill.paid
        %td.green
      - else
        %td.red
      %td= user_bill.bill.due


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/users/welcome.html.haml
- content_for(:title, 'Welcome')

%p Here are your bills:

%table
  %tr
    %th Amount
    %th Name
    %th Description
    %th Due
    %th Paid
    %th

  - @user_bills.each do |user_bill|
    %tr
      %td= user_bill.bill.amount
      %td= user_bill.bill.name
      %td= user_bill.bill.description
      %td= user_bill.bill.due
      - if user_bill.paid
        %td.green
      - else
        %td.red
      %td= link_to "Mark as Paid", user_bill_mark_as_paid_path(user_bill)

%table
  %tr
    %th Number of Bills
    %th Total Due
  %tr
    %td= @user_bills.count
    %td= @sum
    