config/routes.rb
MoneyManagement::Application.routes.draw do
  
  resources :bills
  
  resources :user_bills do
    get :mark_as_paid
  end

  match '/users/login' => 'users#login'
  match '/users/logout' => 'users#logout'
  match '/users/welcome' => 'users#welcome'
  match '/user_bills/mark_as_paid' => 'user_bills#mark_as_paid'

  resources :users do
    get :login
    post :login
  end
    
  get "admin/index"

  root :to => "users#welcome"
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  
  has_many :user_bills, :dependent => :destroy
  has_many :users, :through => :user_bills
  
  def to_label
    "#{due.to_s} #{name}"
  end
  
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  
  before_filter :admin_required
  
  # GET /bills
  # GET /bills.xml
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.xml
  def show
    @bill = Bill.find(params[:id])
    @user_bills = UserBill.where("bill_id = ?", params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.xml
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.xml
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to(@bill, :notice => 'Bill was successfully created.') }
        format.xml  { render :xml => @bill, :status => :created, :location => @bill }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.xml
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to(@bill, :notice => 'Bill was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.xml
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to(bills_url, :notice => "Bill was successfully removed.") }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.haml
= semantic_form_for @bill do |f|
  = f.inputs
  = f.buttons

app/views/bills/edit.html.haml
- content_for(:title, 'Edit Bill')

%h1 Editing bill

= render 'form'

= link_to 'Show', @bill
\|
= link_to 'Back', bills_path

app/views/bills/index.html.haml
- content_for(:title, 'Manage Bills')

%h1 Listing bills

%table
  %tr
    %th Amount
    %th Name
    %th Description
    %th Due
    %th
    %th
    %th

  - @bills.each do |bill|
    %tr
      %td= bill.amount
      %td= bill.name
      %td= bill.description
      %td= bill.due
      %td= link_to 'Show', bill
      %td= link_to 'Edit', edit_bill_path(bill)
      %td= link_to 'Destroy', bill, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Bill', new_bill_path

app/views/bills/new.html.haml
- content_for(:title, 'New Bill')

%h1 New bill

= render 'form'

= link_to 'Back', bills_path

app/views/bills/show.html.haml
- content_for(:title, 'Bill')

%h1 Bill Information

%p#notice= notice

%p
  %b Amount:
  = @bill.amount

%p
  %b Name:
  = @bill.name

%p
  %b Description:
  = @bill.description

%p
  %b Due
  = @bill.due


= link_to 'Edit', edit_bill_path(@bill)
\|
= link_to 'Back', bills_path

%p
  %h1 Users with this bill

%table
  %tr
    %th Username
    %th Paid
    %th

  - @user_bills.each do |user_bill|
    %tr
      %td= user_bill.user.username
      - if user_bill.paid
        %td.green
      - else
        %td.red
      %td= link_to "Mark as Paid", user_bill_mark_as_paid_path(user_bill)