config/routes.rb
MoneyManagement::Application.routes.draw do
  
  resources :bills
  
  resources :user_bills do
    get :mark_as_paid
  end

  match '/users/login' => 'users#login'
  match '/users/logout' => 'users#logout'
  match '/users/welcome' => 'users#welcome'
  match '/user_bills/mark_as_paid' => 'user_bills#mark_as_paid'

  resources :users do
    get :login
    post :login
  end
    
  get "admin/index"

  root :to => "users#welcome"
end

app/models/user_bill.rb
class UserBill < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :bill
  
end

app/controllers/user_bills_controller.rb
class UserBillsController < ApplicationController
  
  before_filter :admin_required, :only => ['index', 'show', 'new', 'edit', 'create', 'update', 'destroy']
  
  # GET /user_bills
  # GET /user_bills.xml
  def index
    @user_bills = UserBill.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_bills }
    end
  end

  # GET /user_bills/1
  # GET /user_bills/1.xml
  def show
    @user_bill = UserBill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_bill }
    end
  end

  # GET /user_bills/new
  # GET /user_bills/new.xml
  def new
    @user_bill = UserBill.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_bill }
    end
  end

  # GET /user_bills/1/edit
  def edit
    @user_bill = UserBill.find(params[:id])
  end

  # POST /user_bills
  # POST /user_bills.xml
  def create
    if params[:user_bill][:user_id] == ""
      @users = User.all
      @users.each do |user|
        @user_bill = UserBill.new(
          :paid => params[:user_bill][:paid], 
          :bill_id => params[:user_bill][:bill_id],
          :user_id => user.id
        )
        @user_bill.save
      end
    else
      @user_bill = UserBill.new(params[:user_bill])
      @user_bill.save
    end

    # respond_to do |format|
    #   if @user_bill.save
    #     format.html { redirect_to(@user_bill, :notice => 'User bill was successfully created.') }
    #     format.xml  { render :xml => @user_bill, :status => :created, :location => @user_bill }
    #   else
    #     format.html { render :action => "new" }
    #     format.xml  { render :xml => @user_bill.errors, :status => :unprocessable_entity }
    #   end
    # end
    
    redirect_to(@user_bill, :notice => 'User bill was successfully created.')
  end

  # PUT /user_bills/1
  # PUT /user_bills/1.xml
  def update
    @user_bill = UserBill.find(params[:id])

    respond_to do |format|
      if @user_bill.update_attributes(params[:user_bill])
        format.html { redirect_to(@user_bill, :notice => 'User bill was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_bills/1
  # DELETE /user_bills/1.xml
  def destroy
    @user_bill = UserBill.find(params[:id])
    @user_bill.destroy

    respond_to do |format|
      format.html { redirect_to(user_bills_url, :notice => "User bill was successfully removed") }
      format.xml  { head :ok }
    end
  end
  
  def mark_as_paid
    @user_bill = UserBill.find(params[:user_bill_id])
    @user_bill.paid = true
    @user_bill.save
    redirect_to(:back, :notice => "User bill has now been paid")
  end
  
end

app/helpers/user_bills_helper.rb
module UserBillsHelper
end

app/views/user_bills/_form.html.haml
= semantic_form_for @user_bill do |f|
  = f.inputs do
    = f.input :bill, :include_blank => false
    = f.input :user
    = f.input :paid
  = f.buttons

app/views/user_bills/edit.html.haml
- content_for(:title, 'Edit User Bill')

%h1 Editing User Bill

= render 'form'

= link_to 'Show', @user_bill
\|
= link_to 'Back', user_bills_path

app/views/user_bills/index.html.haml
- content_for(:title, 'User Bills')

%h1 Listing User Bills

%table
  %tr
    %th Bill
    %th Due
    %th Amount
    %th User
    %th Paid
    %th
    %th
    %th
    %th

  - @user_bills.each do |b|      
    %tr
      %td= link_to b.bill.name, bill_path(b.bill)
      %td= b.bill.due
      %td= b.bill.amount
      %td= b.user.username
      - if b.paid
        %td.green
      - else
        %td.red
      %td= link_to 'Show', b
      %td= link_to 'Edit', edit_user_bill_path(b)
      %td= link_to 'Destroy', b, :method => :delete
      %td= link_to "Mark as Paid", user_bill_mark_as_paid_path(b)

%br

= link_to 'New User bill', new_user_bill_path

app/views/user_bills/new.html.haml
- content_for(:title, 'New User Bill')

%h1 New User Bill

= render 'form'

= link_to 'Back', user_bills_path

app/views/user_bills/show.html.haml
- content_for(:title, 'User Bill')

%h1 User Bill

%p#notice= notice

%p
  %b Bill:
  = @user_bill.bill.name
  
%p
  %b User:
  = @user_bill.user.username

%p
  %b Paid:
  = @user_bill.paid


= link_to 'Edit', edit_user_bill_path(@user_bill)
\|
= link_to 'Back', user_bills_path