config/routes.rb
MoneyManagement::Application.routes.draw do
  
  resources :bills
  
  resources :user_bills do
    get :mark_as_paid
  end

  match '/users/login' => 'users#login'
  match '/users/logout' => 'users#logout'
  match '/users/welcome' => 'users#welcome'
  match '/user_bills/mark_as_paid' => 'user_bills#mark_as_paid'

  resources :users do
    get :login
    post :login
  end
    
  get "admin/index"

  root :to => "users#welcome"
end

app/views/layouts/application.html.haml
!!!
%html{ :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %title= yield_for(:title, '') + ' - Money Management'
    = stylesheet_link_tag :all, :recursive => true
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "rails", "application", "filter"
    = csrf_meta_tag

  %body
    #wrapper
      #header
        #current-user
          - if session[:user]
            Logged in as: #{session[:user]} (#{link_to "Log out", users_logout_path})
        #title
          Money Management
      #menu
        %ul.button-list
          %li= link_to 'Home', users_welcome_path, :class => "button"
          - if session[:user] && session[:user][:admin]
            %li= link_to 'Admin', admin_index_path, :class => "button"
            %li= link_to 'Manage Bills', bills_path, :class => "button"
            %li= link_to 'Manage Users', users_path, :class => "button"
            %li= link_to 'User Bills', user_bills_path, :class => "button"
      #frame
        #content
          - if notice
            .flash
              .notice
                %p= notice
          - if alert
            .flash
              .alert
                %p= alert
              
          = yield

      #footer
        &copy; #{Date.today.year} TerraCoding